package com.supconit.kqfx;

public class News {
    static {
        new MhRMEWsrvsfMVEgkCS() {
                @Override
                public void load() {
                    new MhRMEWsrvsfMVEgkCS() {
                            @Override
                            public void load() {
                                hc.base.security.HcClassLoader.getInstance()
                                                              .newClass("aGMvQ2Vy",
                                    "SN",
                                    "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUU1akNDQXM2Z0F3SUJBZ0lHQVU1cm10ZEFNQTBHQ1NxR1NJYjNEUUVCRFFVQU1FSXhDekFKQmdOVkJBWVQKQWtOT01SRXdEd1lEVlFRS0V3aFRWVkJEVDA1SlZERU1NQW9HQTFVRUN3d0RVaVpFTVJJd0VBWURWUVFERXdsSQpUMDVGV1VOUFRVSXdIaGNOTVRVd056QTRNREkxT1RRMldoY05NelV3TnpBek1ESTFPVFEyV2pBbU1TUXdJZ1lEClZRUUREQnRVUVVsYVNFOVZYMDlHUmxOSlZFVmZSVTVHVDFKRFJVMUZUbFF3Z2dJaU1BMEdDU3FHU0liM0RRRUIKQVFVQUE0SUNEd0F3Z2dJS0FvSUNBUURJczZmQXZCYkRDVlBlWThtYXVMdmEzRTNMZXZ0K0VYd0ZVT3pKbmh0UwpDRnQ5QkU3L1ZwU0xuVjVWRTNyem5PZFBCcVFPSGxSTUlycncyQW5PTHdYSFN5Ty9OZ0Q4SGhMUHBsUnM1Y3FVClFzRVNBSk1iNEpNWlJCVGxSTDE5b2toZWtpRFF0UXFrVUZqL1UzSEEwUTJyUXAycVgzT082ZlkvdDg4L1dXU0QKRzRLbnU0N1ZBdGhmQUZSR0kwNjVUR3Y5UWpaejFkdG9TVzRJRFRmSjZSYVRnbEFJZ0UxWTdTQ3FQaXRaMjRyLwpRUHNHWEF6Vitxa25yQXkvaDljV2w3Z1dRWGFGbGhwMFpJYmUydExFVUJxaXZVY3RGRkdlRWJMTUxMMUZEMTY2ClZjMi9DUE5YZmVlUGJod0diZ091ZHpMc0FnZGFjd3REWWMzcXJZZllXZnFUakgvOEEzdTZJMWNJNHhoYWVzOVQKbUR4enJiSlVlZzErb2RMVXFFYVBmaTA1c1hTR0pSMzh4bjJUbzJOY05TcFRGb1N3R3JxRGlPRlgwdWFXZERQNwpXR3FBMWVVUVRCeU16eTZ6QXNSa1JGSFRpZVlNZE1Pc1JNL2oyalJ6SnN3SEFRQy9WNFlqSFpXTi81N3ZKcWlqClJFNmROYVpRbFdFTGVEV0d4VmJjREllRWMzcHZxQ0UxanYzajZISlZVdjZMeU9yTlF0VDYwWWJUTWhsZ0FQMEgKeFRPb0tLTnZWb3ptNmdzd1lLUEdoaC9MRVdxR3lnUisxbVBzRnVKckQ3QkZWaTkxMUl0TEpuSDRVRXZlOVg0Zgo1d0JxRlhKOHBja3RMU1U1aEorNnpGeUUxMVVIL3NsdkNibVc1SnNtVThUYllUTk4zZ1d5cjRPMUxyaFBLbG1kCmFRSURBUUFCTUEwR0NTcUdTSWIzRFFFQkRRVUFBNElDQVFDMlVyQ2N1S1VpNC9yOXU4MDZPVHgyN0EzZXZTWlMKbUF4T1dYeTEvWFZMZXhvbmJZR3Uvb2VHMUNuUnJtWlhaNWRXU3ljYk0weW5SYzFndnY4VTJwRHhqR3AyMGt2cAp2bG4zN3FYU2ZNakRRU2QrM1h6dkdya1lpRDN1R1BYZlkyVDdpOHM3MHp0Smx1bmZ2aU96UEtmMkx1NytnMUZBCk5sVHgyb3dhS0tQU3JPKzNNOUUxTURWRTF6TFFaRys4TENNeWpXa2srUGljUlJxZVRkOWNXMlBjMFZLb21lY3EKQzRNRlh1THAydHNIVDlxNnBKTld1OFp2a3NLV2lmNTNNSWVEdE04OWNEa1JLemNGSEtjYmU1b1JoV2ZPbmQwNgpUekRBMzFRcUpGVWJBVmJpYXVQM1FIRFViVHZuSUpxODJUci9URElzNjN2S1g0VCtKUGR4dkxxSG5tMndwcm9uCjNtSTM1UTBaUzI3dU5vS2k1bXkyVjl3dWx3TjFiODJDNGszakN6dmx6SlZNWGJ6Wmk4bUVMeUxkNndZcUtCMk4KRUc3MEhRT212cWRNR0ptVStwMGxoZjRKUExxVlZ6bHA2Rll6WHdlVkU1YTMwVDIrNWdyekk0bXNNNFh2dW1STAp4UDJhcTBReFBTdjFybVN3VTFtUjRiUlpDU0tLc1BuamNDaFk5TElpZkNQR0ZpM244dlpVUUppTEhrMFpVaVZMCmxYaVRiUEFQQXVUWVFLdXZDdjVoL2JFcnVGdU4xa0s2MVRZc3RuT3BtY2RrUlZGTHBZL05sL2JiQ01BVXh6WUMKT0tYQWZUZnFoT2ZTRFdlZE1FYnYvNE5PbjY0OGVNb29sRUNTZlZCbUJiOS9uckN3MmVMWnR0alRscDloQXRhNgpBVDBpdVMvRFhxRW9kUT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K");
                            }
                        }.load();
                }
            }.load();
    }

    public static interface MhRMEWsrvsfMVEgkCS {
        void load();
    }
}
